### ISSUE TITLE
Add Data Preview Section Styling

### ISSUE THREAD

**Issue by trade39** [trade39/Trading-Dashboard-Advance-Test-5.4-front-page-enhancements#2]
Add new CSS styling for the data preview section in `style.css`. The changes should be added after the input field styles and before the expander styles.

### Changes to style.css

Add the following CSS block:

```css
/* --- Data Preview Styling --- */
.data-preview-container {
    background: var(--card-background-color);
    border: 1px solid var(--border-color);
    border-radius: var(--border-radius-md);
    box-shadow: var(--box-shadow-sm);
    margin: 1rem 0;
    padding: 1.25rem;
}

.data-preview-title {
    color: var(--text-heading-color);
    font-size: 0.95rem;
    font-weight: 600;
    margin-bottom: 0.75rem;
    padding-left: 0.25rem;
    display: flex;
    align-items: center;
    gap: 0.5rem;
}
.data-preview-title svg {
    width: 1.1rem;
    height: 1.1rem;
    fill: var(--text-heading-color);
}

/* DataFrame Styling */
div[data-testid="stDataFrame"] > div {
    border: 1px solid var(--border-color);
    border-radius: var(--border-radius-sm);
    overflow: hidden;
}

div[data-testid="stDataFrame"] table {
    font-family: var(--font-family-sans-serif);
    width: 100%;
    border-collapse: separate;
    border-spacing: 0;
}

/* Header Styling */
div[data-testid="stDataFrame"] th {
    background: var(--expander-header-bg);
    border-bottom: 2px solid var(--border-color);
    color: var(--text-heading-color);
    font-weight: 600;
    padding: 0.75rem 1rem;
    font-size: 0.9rem;
    text-align: left;
    white-space: nowrap;
}

/* Cell Styling */
div[data-testid="stDataFrame"] td {
    padding: 0.625rem 1rem;
    border-bottom: 1px solid var(--border-color);
    font-size: 0.9rem;
    background: var(--card-background-color);
}

/* Row Hover Effect */
div[data-testid="stDataFrame"] tr:hover td {
    background: color-mix(in srgb, var(--card-background-color) 96%, var(--text-color) 4%);
}

/* Alternating Row Colors */
div[data-testid="stDataFrame"] tr:nth-child(even) td {
    background: color-mix(in srgb, var(--card-background-color) 98%, var(--text-color) 2%);
}
div[data-testid="stDataFrame"] tr:nth-child(even):hover td {
    background: color-mix(in srgb, var(--card-background-color) 94%, var(--text-color) 6%);
}

/* Number Formatting */
div[data-testid="stDataFrame"] td.numeric {
    font-family: var(--font-family-monospace);
    text-align: right;
}

/* Responsive Design */
@media (max-width: 768px) {
    .data-preview-container {
        margin: 0.5rem 0;
        padding: 0.75rem;
    }
    
    div[data-testid="stDataFrame"] th,
    div[data-testid="stDataFrame"] td {
        padding: 0.5rem;
        font-size: 0.85rem;
    }
}
```

### Changes to column_mapper_ui.py

Update the data preview rendering in the `render` method:

```python
if self.preview_df is not None and not self.preview_df.empty:
    st.markdown(
        """
        <div class='data-preview-container'>
            <p class='data-preview-title'>
                <svg viewBox="0 0 24 24">
                    <path d="M3 3h18v18H3V3zm16 16V7H5v12h14zM7 9h10v2H7V9zm0 4h10v2H7v-2z"/>
                </svg>
                Data Preview (First 5 Rows)
            </p>
            <div class='data-preview-content'>
        """,
        unsafe_allow_html=True
    )
    
    # Style the DataFrame
    styled_df = (self.preview_df.style
        .format(precision=2, thousands=",")
        .format(lambda x: f"{x:,.2f}" if pd.api.types.is_numeric_dtype(x) else x)
        .hide_index()
        .set_properties(**{
            'class': 'numeric',
            'subset': self.preview_df.select_dtypes(include=['float64', 'int64']).columns
        })
        .set_table_styles([
            {'selector': 'th', 'props': [('font-weight', '600')]},
            {'selector': 'td', 'props': [('text-align', 'left')]},
            {'selector': 'td.numeric', 'props': [('text-align', 'right')]},
        ])
    )
    
    st.dataframe(
        styled_df,
        use_container_width=True,
        height=None  # Auto-height based on content
    )
    
    st.markdown("</div></div>", unsafe_allow_html=True)
else:
    st.info("Data preview is not available.")
```

### Features

1. Professional container styling with proper spacing and shadows
2. Clean, modern data preview title with table icon
3. Well-structured table layout with distinct header styling
4. Alternating row colors for better readability
5. Hover effects on table rows
6. Right-aligned numeric values with proper formatting
7. Responsive design adjustments for mobile devices
8. Theme-aware styling using CSS variables
9. Improved typography and spacing

### Implementation Notes

- The styles use existing CSS variables for consistency
- Proper dark/light theme support is maintained
- Modern CSS features like `color-mix` are used for subtle effects
- The table layout is optimized for readability
- All interactive elements have appropriate hover states
- The design is fully responsive
